




@startuml MainMenuClassDiagram


top to bottom direction

package "Main Menu" {

    package Buttons <<Node>> {

        +Class "SinglePlayerButton" as SinglePlayerButtonClass {

        }

        +Class "MultiplayerButton" as MultiplayerButtonClass {
            
        }

        +Class "HighScoresButton" as HighScoresButtonClass {
            // Shows HighScores on Screen
        }

        +Class "CreditsButton" as CreditsButtonClass {
            // Shows Credits
        }

        +Class "ExitButton" as ExitButtonClass {

        }

    }

    package Shared <<Node>> {

        +Class "Settings" as SettingsClass {
            In Settings Class Diagram
        }

       +Class "PlayerInfo" as PlayerInfoClass{
            In Settings Class Diagram
        }


    }




}


@enduml























