

@startuml MainMenuClassDiagram


top to bottom direction

package "Main Menu" {





    package ScreenUI <<Node>> {

        +Class "GamesList" as GamesListClass {
            +Int JoinedPlayers
            +Int MaxPlayers
            +String SessionName
            +FlagType Flag
            +Boolean isPasswordProtected
            +Boolean isFriendsOnly
            +String Password
        }


    }







    package Buttons <<Node>> {

        +Class "JoinGameButton" as JoinGameButtonClass {

        }

        +Class "BackButton" as BackButtonClass {
            
        }

        +Class "HostGameButton" as HighScoresButtonClass {
            // Dialog
            +String SessionName
            +FlagType Flag
            +Boolean isPasswordProtected
            +Boolean isFriendsOnly
            +String Password
            +Int MaxPlayers

        }

    }






    package Shared <<Node>> {

        

        +Class "PlayerInfo" as PlayerInfoClass{
            In Settings Class Diagram
        }


    }




}


@enduml



